// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxppflscazhgoikzzxha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4cHBmbHNjYXpoZ29pa3p6eGhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDIzMzIsImV4cCI6MjA2Nzg3ODMzMn0.LLXKdrL_xlmNT88naJCVf99Qs09frIxMeQdWmqRxOAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});